# Generated by Django 3.2.9 on 2021-11-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobs',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='reward',
            field=models.TextField(default=0),
        ),
    ]
