# Generated by Django 3.2.8 on 2021-10-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bounty',
            name='reward',
            field=models.CharField(max_length=200),
        ),
    ]
