# Generated by Django 3.2.9 on 2021-11-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211119_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
